---
  - name: Set SELinux to permissive mode (требования kubeadm)
    selinux:
      policy: targeted
      state: permissive
    notify: Reboot host 

# Лучше для продакшена так не делать, тут хорошо бы настроить политики фаервола, но в случае лабы - можем такое позволить 
  - name: Stop firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
 # Отключаем swap память до перезагрузки (ухудшает производительность, ошибки планирования)
  - name: Disable swap immediately
    command: swapoff -a
    changed_when: false
# В файле настроек монтирования дисков удаляем строчки, начинающиеся с *swap, чтобы swap память не включалась после перезагрузки 
  - name: Disable swap permanently
    lineinfile:
      path: /etc/fstab
      regexp: '^.*swap'
      state: absent

  - name: Load kernel module br_netfilter
    modprobe:
      name: br_netfilter
      state: present

  - name: Ensure br_netfilter loads on boot
    copy:
      dest: /etc/modules-load.d/br_netfilter.conf
      content: "br_netfilter"
      mode: 0644

  - name: Configure kernel parametrs 
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      reload: yes
    loop:
      - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
      - { name: net.ipv4.ip_forward, value: 1 }

  - name: Add Kubernetes repository
    yum_repository:
      name: kubernetes
      description: Kubernetes repository
      baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/rpm/"
      gpgkey: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/rpm/repodata/repomd.xml.key"
      repo_gpgcheck: yes
      gpgcheck: yes
  
  - name: Install Docker prerequisites
    yum:
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: present
  
  - name: Add Docker CE repo
    yum_repository:
      name: docker-ce
      description: Docker CE
      baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/x86_64/stable"
      gpgkey: "https://download.docker.com/linux/centos/gpg"
      gpgcheck: yes
  
  - name: Install Docker CE 
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Ensure /etc/docker exists
    file:
      path: /etc/docker
      state: directory
  
  - name: Configure Docker Daemon
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "storage-driver": "overlay2"
        }
      mode: 0644
  
  - name: Start Docker
    systemd:
      name: docker.service
      state: started
      enabled: yes

    

  - name: Install Kubernetes packages
    yum:
      name:
        - kubelet-{{ kube_version }}.0
        - kubeadm-{{ kube_version }}.0
        - kubectl-{{ kube_version }}.0
      state: present

  - name: Wait after Reboot
    wait_for_connection:
      delay: 30
      timeout: 300