---
- name: Configure CentOS 8 repository after EOL
  hosts: all
  become: yes
  vars:
    centos8_repos:
      - "CentOS-Linux-AppStream.repo"
      - "CentOS-Linux-BaseOS.repo"
      - "CentOS-Linux-Extras.repo"

  tasks:
    - name: Check OS
      ansible.builtin.fail:
        msg: "This playbook works only on CentOS 8"
      when:
        - ansible_distribution != 'CentOS'
        - ansible_distribution_major_version != '8'
      tags: always

    - name: Process repositories 
      block:
        - name: Modify repo files
          ansible.builtin.replace:
            path: "/etc/yum.repos.d/{{ item }}"
            regexp: '(^mirrorlist=)|(^#baseurl=http://mirror.centos.org)'
            replace: |
              #mirrorlist=
              baseurl=http://vault.centos.org
            backup: yes
          loop: "{{ centos8_repos }}"
          register: repo_changes

        - name: Update cache if changes were made
          ansible.builtin.command: |
            dnf clean --all
            dnf makecache
          when: repo_changes.changed

      rescue:
        - name: Restore original repos on error
          ansible.builtin.command: |
            find /etc/yum.repos.d/ -name "*.repo.bak" -exec mv {} {}.bak \;
          when: "'repo_changes' in vars"