all: 
  hosts:
    kube-master:
      ansible_host: 192.168.56.10
      host_port: 8080
      vm_name: master
    kube-worker1:
      ansible_host: 192.168.56.11
      host_port: 8081
      vm_name: worker1
    kube-worker2:
      ansible_host: 192.168.56.12
      host_port: 8082
      vm_name: worker2
  
  children:
    all:
      k8s-cluster:
        kube-master:
        kube-worker1:
        kube-worker2:
    
    k8s-masters:
      hosts:
        kube-master:
    
    k8s-workers:
      hosts:
        kube-worker1:
        kube-worker2:

