all: 
  hosts:
    kube-master:
    kube-worker1:
    kube-worker2:
  
  children:
    all:
      k8s-cluster:
        kube-master:
        kube-worker1:
        kube-worker2:
    
    k8s-control-plane:
      hosts:
        kube-master:
    
    k8s-workers:
      hosts:
        kube-worker1:
        kube-worker2:

