all:
  hosts:
    kube_master:
    kube_worker1:
    kube_worker2:
  
  children:
    k8s_cluster:
      hosts:
        kube_master:
        kube_worker1:
        kube_worker2:
    
    k8s_control_plane:
      hosts:
        kube_master:
    
    k8s_workers:
      hosts:
        kube_worker1:
        kube_worker2:

